### PR TITLE
Linux build

### PR DESCRIPTION
**Pull request by igorangst**
Lightweight adaptations for a linux build of kerberos, using ALSA or JACK drivers. Fixes a timing issue, where fast sysex messages were dropped. Also added a convenient build script that populates the kerberos release directory with the binary, dependency libs and a startup script. Have fun!

### CODE REVIEW

**Comment by johey** [comment]
The build script fails because of missing Makefile. Forgot to add it?

**Comment by igorangst** [comment]
Hi,

the Makefile is being generated by qmake, which I forgot to call in the
build script. Should work now. Please test again.

Ulrich

**Comment by johey** [comment]
It works fine now. Thanks! Just had to apt-get install qt5-default and all dependencies were installed (Ubuntu 14.04). Though, I don't know why but the change is not added in master branch. I had to add it myself into the build script even though I pulled from master.

**Comment by meonwax** [comment]
Any plans to merge this?

**Comment by j0ju** [comment]
Hi, tried this branch, but having troubles. 
I tried to compile under jessie and 14.04.

> joju@lx:usr/src/build/c64-midi-kerberos-git/qt# sh build-linux.sh 
> [*] Building application
> g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -D__LINUX_ALSASEQ__ -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../../../lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../../../../include/qt5 -I../../../../include/qt5/QtWidgets -I../../../../include/qt5/QtGui -I../../../../include/qt5/QtCore -I. -I. -o mainwindow.o mainwindow.cpp
> In file included from mainwindow.h:11:0,
>                  from mainwindow.cpp:12:
> ui_mainwindowform.h:13:25: fatal error: QtGui/QAction: No such file or directory
>  #include <QtGui/QAction>
>                          ^
> compilation terminated.
> make: *** [mainwindow.o] Error 1
> [*] Could not build application

I installed `qt5-default` as mentioned. In Jessie oder Ubuntu 14.04 there is not a file in` /usr/include/x86_64-linux-gnu/qt5/QtGui/QAction` only  `/usr/include/x86_64-linux-gnu/qt5/QtGui/QActionInterface`.

What I am missing?

**Comment by meonwax** [comment]
I didn't use the `build-linux.sh` script, just compiled manually:
```
cd qt
qmake
make
```

Then the resulting `kerberos.bin` works just fine.
Why would i need the librarys bundled in a `lib`-directory as the `build-linux.sh` script copies them?
They are dynamically linked and just exist on my system.

**Comment by igorangst** [comment]
As requested in the [original issue](https://github.com/FrankBuss/kerberos/issues/1), I tried to provide a more or less static build that could be deployed on systems that don't have all the libraries readily installed. It seems that my solution is not as portable as it should be. I suggest to split up the build script in a "just build" (i.e. qmake & make) and a "build release", which would include the library copying stuff. Any better idea?

**Comment by meonwax** [comment]
Would it be possible to statically link the libraries, so only the binary has to be deployed?

**Comment by j0ju** [comment]
I got i to build in a clean Debian/Jessie chroot. I have not tested the application yet.

The following packages I had to install:
> qt5-default 
> libasound-dev

This patch let my trouble go away, as in an qmake run `Makefile` and `ui_mainwindowform.h` are rebuild, if there is an  `ui_mainwindowform.h` lying around from a former try it might fail.

> --- a/qt/build-linux.sh
> +++ b/qt/build-linux.sh
> @@ -16,6 +16,7 @@ then
>  fi
>  
>  echo "[*] Building application"
> +rm -f Makefile ui_mainwindowform.h
>  qmake
>  make
>

**Comment by j0ju** [comment]
With less white space fixes and the above patch you can find it here. https://github.com/j0ju/kerberos/commit/5a735738dcba222169bc444db37942c74ba21daf

**Pull request merged**
